/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import 'sst'
export {}
declare module 'sst' {
  export interface Resource {
    BOOKMARKER_AUTH_SECRET: {
      type: 'sst.sst.Secret'
      value: string
    }
    BOOKMARKER_DATABASE_URL: {
      type: 'sst.sst.Secret'
      value: string
    }
    BOOKMARKER_GOOGLE_CLIENT_ID: {
      type: 'sst.sst.Secret'
      value: string
    }
    BOOKMARKER_GOOGLE_CLIENT_SECRET: {
      type: 'sst.sst.Secret'
      value: string
    }
    BookmarkerWeb: {
      type: 'sst.aws.Remix'
      url: string
    }
  }
}
